# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1863, 1006)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setWordWrap(True)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_5.addWidget(self.tableView)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.searchTab = QtWidgets.QWidget()
        self.searchTab.setObjectName("searchTab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.searchTab)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.searchGroup = QtWidgets.QGroupBox(self.searchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchGroup.sizePolicy().hasHeightForWidth())
        self.searchGroup.setSizePolicy(sizePolicy)
        self.searchGroup.setObjectName("searchGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.searchGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.keywordsLine = QtWidgets.QLineEdit(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keywordsLine.sizePolicy().hasHeightForWidth())
        self.keywordsLine.setSizePolicy(sizePolicy)
        self.keywordsLine.setObjectName("keywordsLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.keywordsLine)
        self.label_2 = QtWidgets.QLabel(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.searchIndexList = QtWidgets.QListWidget(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchIndexList.sizePolicy().hasHeightForWidth())
        self.searchIndexList.setSizePolicy(sizePolicy)
        self.searchIndexList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.searchIndexList.setObjectName("searchIndexList")
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.searchIndexList.addItem(item)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.searchIndexList)
        self.label_3 = QtWidgets.QLabel(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minPriceSearchBox = QtWidgets.QDoubleSpinBox(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minPriceSearchBox.sizePolicy().hasHeightForWidth())
        self.minPriceSearchBox.setSizePolicy(sizePolicy)
        self.minPriceSearchBox.setMaximum(9999.0)
        self.minPriceSearchBox.setProperty("value", 30.0)
        self.minPriceSearchBox.setObjectName("minPriceSearchBox")
        self.horizontalLayout.addWidget(self.minPriceSearchBox)
        self.label_4 = QtWidgets.QLabel(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.maxPriceSearchBox = QtWidgets.QDoubleSpinBox(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxPriceSearchBox.sizePolicy().hasHeightForWidth())
        self.maxPriceSearchBox.setSizePolicy(sizePolicy)
        self.maxPriceSearchBox.setMaximum(9999.0)
        self.maxPriceSearchBox.setProperty("value", 150.0)
        self.maxPriceSearchBox.setObjectName("maxPriceSearchBox")
        self.horizontalLayout.addWidget(self.maxPriceSearchBox)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchButton = QtWidgets.QPushButton(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_2.addWidget(self.searchButton)
        self.cancelSearchButton = QtWidgets.QPushButton(self.searchGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelSearchButton.sizePolicy().hasHeightForWidth())
        self.cancelSearchButton.setSizePolicy(sizePolicy)
        self.cancelSearchButton.setObjectName("cancelSearchButton")
        self.horizontalLayout_2.addWidget(self.cancelSearchButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addWidget(self.searchGroup)
        self.filterGroup = QtWidgets.QGroupBox(self.searchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterGroup.sizePolicy().hasHeightForWidth())
        self.filterGroup.setSizePolicy(sizePolicy)
        self.filterGroup.setObjectName("filterGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.filterGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_3 = QtWidgets.QFrame(self.filterGroup)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.applyFiltersButton = QtWidgets.QPushButton(self.filterGroup)
        self.applyFiltersButton.setObjectName("applyFiltersButton")
        self.horizontalLayout_6.addWidget(self.applyFiltersButton)
        self.revertFiltersButton = QtWidgets.QPushButton(self.filterGroup)
        self.revertFiltersButton.setObjectName("revertFiltersButton")
        self.horizontalLayout_6.addWidget(self.revertFiltersButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 2, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.filterGroup)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.filterDateBox = QtWidgets.QComboBox(self.filterGroup)
        self.filterDateBox.setObjectName("filterDateBox")
        self.filterDateBox.addItem("")
        self.filterDateBox.addItem("")
        self.filterDateBox.addItem("")
        self.filterDateBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.filterDateBox)
        self.label_10 = QtWidgets.QLabel(self.filterGroup)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.primeCheck = QtWidgets.QCheckBox(self.filterGroup)
        self.primeCheck.setChecked(True)
        self.primeCheck.setObjectName("primeCheck")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.primeCheck)
        self.amazonCheck = QtWidgets.QCheckBox(self.filterGroup)
        self.amazonCheck.setChecked(True)
        self.amazonCheck.setObjectName("amazonCheck")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.amazonCheck)
        self.privateLabelCheck = QtWidgets.QCheckBox(self.filterGroup)
        self.privateLabelCheck.setChecked(True)
        self.privateLabelCheck.setObjectName("privateLabelCheck")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.privateLabelCheck)
        self.restrictedCheck = QtWidgets.QCheckBox(self.filterGroup)
        self.restrictedCheck.setChecked(True)
        self.restrictedCheck.setObjectName("restrictedCheck")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.restrictedCheck)
        self.zeroesCheck = QtWidgets.QCheckBox(self.filterGroup)
        self.zeroesCheck.setChecked(True)
        self.zeroesCheck.setObjectName("zeroesCheck")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.zeroesCheck)
        self.label_6 = QtWidgets.QLabel(self.filterGroup)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.offersFilterBox = QtWidgets.QSpinBox(self.filterGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offersFilterBox.sizePolicy().hasHeightForWidth())
        self.offersFilterBox.setSizePolicy(sizePolicy)
        self.offersFilterBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.offersFilterBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.offersFilterBox.setObjectName("offersFilterBox")
        self.horizontalLayout_4.addWidget(self.offersFilterBox)
        self.label_9 = QtWidgets.QLabel(self.filterGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.formLayout_3.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_7 = QtWidgets.QLabel(self.filterGroup)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minPriceFilterBox = QtWidgets.QDoubleSpinBox(self.filterGroup)
        self.minPriceFilterBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minPriceFilterBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.minPriceFilterBox.setMaximum(99999.0)
        self.minPriceFilterBox.setObjectName("minPriceFilterBox")
        self.horizontalLayout_3.addWidget(self.minPriceFilterBox)
        self.label_8 = QtWidgets.QLabel(self.filterGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.maxPriceFilterBox = QtWidgets.QDoubleSpinBox(self.filterGroup)
        self.maxPriceFilterBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxPriceFilterBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.maxPriceFilterBox.setMaximum(99999.0)
        self.maxPriceFilterBox.setObjectName("maxPriceFilterBox")
        self.horizontalLayout_3.addWidget(self.maxPriceFilterBox)
        self.formLayout_3.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_36 = QtWidgets.QLabel(self.filterGroup)
        self.label_36.setObjectName("label_36")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.withKeywordsLine = QtWidgets.QLineEdit(self.filterGroup)
        self.withKeywordsLine.setObjectName("withKeywordsLine")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.withKeywordsLine)
        self.label_37 = QtWidgets.QLabel(self.filterGroup)
        self.label_37.setObjectName("label_37")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.withoutKeywordsLine = QtWidgets.QLineEdit(self.filterGroup)
        self.withoutKeywordsLine.setObjectName("withoutKeywordsLine")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.withoutKeywordsLine)
        self.label_32 = QtWidgets.QLabel(self.filterGroup)
        self.label_32.setObjectName("label_32")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.rankFilterBox = QtWidgets.QSpinBox(self.filterGroup)
        self.rankFilterBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rankFilterBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rankFilterBox.setMaximum(999999999)
        self.rankFilterBox.setObjectName("rankFilterBox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rankFilterBox)
        self.label_33 = QtWidgets.QLabel(self.filterGroup)
        self.label_33.setObjectName("label_33")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(self.filterGroup)
        self.label_34.setObjectName("label_34")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.weightFilterBox = QtWidgets.QDoubleSpinBox(self.filterGroup)
        self.weightFilterBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weightFilterBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.weightFilterBox.setDecimals(1)
        self.weightFilterBox.setMaximum(99999.0)
        self.weightFilterBox.setObjectName("weightFilterBox")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.weightFilterBox)
        self.volumeFilterBox = QtWidgets.QDoubleSpinBox(self.filterGroup)
        self.volumeFilterBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.volumeFilterBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.volumeFilterBox.setDecimals(1)
        self.volumeFilterBox.setMaximum(99999.0)
        self.volumeFilterBox.setObjectName("volumeFilterBox")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.volumeFilterBox)
        self.gridLayout_2.addLayout(self.formLayout_4, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.horizontalLayout_5.addWidget(self.filterGroup)
        self.groupBox_2 = QtWidgets.QGroupBox(self.searchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchStatusList = QtWidgets.QListWidget(self.groupBox_2)
        self.searchStatusList.setResizeMode(QtWidgets.QListView.Adjust)
        self.searchStatusList.setObjectName("searchStatusList")
        self.verticalLayout_3.addWidget(self.searchStatusList)
        self.clearSearchStatusBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.clearSearchStatusBtn.setObjectName("clearSearchStatusBtn")
        self.verticalLayout_3.addWidget(self.clearSearchStatusBtn)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.tabWidget.addTab(self.searchTab, "")
        self.detailTab = QtWidgets.QWidget()
        self.detailTab.setObjectName("detailTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.detailTab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.detailTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 375))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1786, 375))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.prodManufacturerLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.prodManufacturerLine.setReadOnly(True)
        self.prodManufacturerLine.setObjectName("prodManufacturerLine")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prodManufacturerLine)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.prodMpnLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.prodMpnLine.setReadOnly(True)
        self.prodMpnLine.setObjectName("prodMpnLine")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prodMpnLine)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.prodASINLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.prodASINLine.setReadOnly(True)
        self.prodASINLine.setObjectName("prodASINLine")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.prodASINLine)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.prodGroupLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.prodGroupLine.setObjectName("prodGroupLine")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.prodGroupLine)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.prodCategoryBox = QtWidgets.QComboBox(self.groupBox_4)
        self.prodCategoryBox.setObjectName("prodCategoryBox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.prodCategoryBox)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.prodSalesRankLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.prodSalesRankLine.setReadOnly(True)
        self.prodSalesRankLine.setObjectName("prodSalesRankLine")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.prodSalesRankLine)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.prodUPCLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.prodUPCLine.setReadOnly(True)
        self.prodUPCLine.setObjectName("prodUPCLine")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.prodUPCLine)
        self.gridLayout_6.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.prodTitleLine = QtWidgets.QLineEdit(self.groupBox)
        self.prodTitleLine.setCursorPosition(0)
        self.prodTitleLine.setReadOnly(True)
        self.prodTitleLine.setObjectName("prodTitleLine")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prodTitleLine)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.prodUrlLine = QtWidgets.QLineEdit(self.groupBox)
        self.prodUrlLine.setCursorPosition(0)
        self.prodUrlLine.setReadOnly(True)
        self.prodUrlLine.setObjectName("prodUrlLine")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prodUrlLine)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 4, 0, 1, 1)
        self.myPriceBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.myPriceBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.myPriceBox.setReadOnly(False)
        self.myPriceBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.myPriceBox.setMaximum(9999.0)
        self.myPriceBox.setObjectName("myPriceBox")
        self.gridLayout_3.addWidget(self.myPriceBox, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fbaFeesBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.fbaFeesBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fbaFeesBox.setMaximum(9999.0)
        self.fbaFeesBox.setObjectName("fbaFeesBox")
        self.horizontalLayout_8.addWidget(self.fbaFeesBox)
        self.getFBAFeesButton = QtWidgets.QToolButton(self.groupBox_5)
        self.getFBAFeesButton.setObjectName("getFBAFeesButton")
        self.horizontalLayout_8.addWidget(self.getFBAFeesButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 5, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 2, 1, 1, 1)
        self.prodOffersBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.prodOffersBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prodOffersBox.setReadOnly(True)
        self.prodOffersBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.prodOffersBox.setMaximum(999)
        self.prodOffersBox.setObjectName("prodOffersBox")
        self.gridLayout_3.addWidget(self.prodOffersBox, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 1, 0, 1, 1)
        self.prodPriceBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.prodPriceBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prodPriceBox.setReadOnly(True)
        self.prodPriceBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.prodPriceBox.setMaximum(9999.0)
        self.prodPriceBox.setObjectName("prodPriceBox")
        self.gridLayout_3.addWidget(self.prodPriceBox, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 0, 0, 1, 1)
        self.myCostBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.myCostBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.myCostBox.setMaximum(9999.0)
        self.myCostBox.setObjectName("myCostBox")
        self.gridLayout_3.addWidget(self.myCostBox, 4, 1, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 5, 0, 1, 1)
        self.monthlyCostBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.monthlyCostBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.monthlyCostBox.setReadOnly(True)
        self.monthlyCostBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monthlyCostBox.setMaximum(9999.0)
        self.monthlyCostBox.setObjectName("monthlyCostBox")
        self.gridLayout.addWidget(self.monthlyCostBox, 4, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 4, 0, 1, 1)
        self.marginBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.marginBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.marginBox.setReadOnly(True)
        self.marginBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.marginBox.setPrefix("")
        self.marginBox.setDecimals(1)
        self.marginBox.setMaximum(9999.0)
        self.marginBox.setObjectName("marginBox")
        self.gridLayout.addWidget(self.marginBox, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 6, 0, 1, 1)
        self.monthlyProfitBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.monthlyProfitBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.monthlyProfitBox.setReadOnly(True)
        self.monthlyProfitBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monthlyProfitBox.setMaximum(9999.0)
        self.monthlyProfitBox.setObjectName("monthlyProfitBox")
        self.gridLayout.addWidget(self.monthlyProfitBox, 5, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.monthlyVolumeBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monthlyVolumeBox.sizePolicy().hasHeightForWidth())
        self.monthlyVolumeBox.setSizePolicy(sizePolicy)
        self.monthlyVolumeBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.monthlyVolumeBox.setDecimals(0)
        self.monthlyVolumeBox.setMaximum(9999.0)
        self.monthlyVolumeBox.setObjectName("monthlyVolumeBox")
        self.horizontalLayout_9.addWidget(self.monthlyVolumeBox)
        self.getVolumeButton = QtWidgets.QToolButton(self.groupBox_5)
        self.getVolumeButton.setObjectName("getVolumeButton")
        self.horizontalLayout_9.addWidget(self.getVolumeButton)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 0, 0, 1, 1)
        self.profitEachBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.profitEachBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.profitEachBox.setReadOnly(True)
        self.profitEachBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.profitEachBox.setMaximum(9999.0)
        self.profitEachBox.setObjectName("profitEachBox")
        self.gridLayout.addWidget(self.profitEachBox, 0, 1, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout)
        self.gridLayout_6.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openAmazonButton = QtWidgets.QPushButton(self.groupBox_3)
        self.openAmazonButton.setObjectName("openAmazonButton")
        self.verticalLayout_2.addWidget(self.openAmazonButton)
        self.openGoogleButton = QtWidgets.QPushButton(self.groupBox_3)
        self.openGoogleButton.setObjectName("openGoogleButton")
        self.verticalLayout_2.addWidget(self.openGoogleButton)
        self.openCamelButton = QtWidgets.QPushButton(self.groupBox_3)
        self.openCamelButton.setObjectName("openCamelButton")
        self.verticalLayout_2.addWidget(self.openCamelButton)
        self.upcLookupButton = QtWidgets.QPushButton(self.groupBox_3)
        self.upcLookupButton.setObjectName("upcLookupButton")
        self.verticalLayout_2.addWidget(self.upcLookupButton)
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.updateButton = QtWidgets.QPushButton(self.groupBox_3)
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout_2.addWidget(self.updateButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.historyStack = QtWidgets.QStackedWidget(self.groupBox_6)
        self.historyStack.setMinimumSize(QtCore.QSize(600, 0))
        self.historyStack.setObjectName("historyStack")
        self.tablePage = QtWidgets.QWidget()
        self.tablePage.setObjectName("tablePage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tablePage)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.obsTable = QtWidgets.QTableView(self.tablePage)
        self.obsTable.setObjectName("obsTable")
        self.gridLayout_5.addWidget(self.obsTable, 0, 0, 1, 1)
        self.historyStack.addWidget(self.tablePage)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.historyStack.addWidget(self.page_2)
        self.horizontalLayout_7.addWidget(self.historyStack)
        self.gridLayout_6.addWidget(self.groupBox_6, 0, 3, 2, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.detailTab, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1863, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionEdit_Categories = QtWidgets.QAction(MainWindow)
        self.actionEdit_Categories.setObjectName("actionEdit_Categories")
        self.actionUpdate_Watched = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Watched.setObjectName("actionUpdate_Watched")
        self.actionRecalculate_Rankings = QtWidgets.QAction(MainWindow)
        self.actionRecalculate_Rankings.setObjectName("actionRecalculate_Rankings")
        self.actionShow_Graph = QtWidgets.QAction(MainWindow)
        self.actionShow_Graph.setCheckable(True)
        self.actionShow_Graph.setObjectName("actionShow_Graph")
        self.actionShow_Table = QtWidgets.QAction(MainWindow)
        self.actionShow_Table.setCheckable(True)
        self.actionShow_Table.setObjectName("actionShow_Table")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuActions.addAction(self.actionEdit_Categories)
        self.menuActions.addAction(self.actionUpdate_Watched)
        self.menuActions.addAction(self.actionRecalculate_Rankings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.historyStack.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Product Finder"))
        self.searchGroup.setTitle(_translate("MainWindow", "Search:"))
        self.label.setText(_translate("MainWindow", "Keywords:"))
        self.label_2.setText(_translate("MainWindow", "Search Index:"))
        __sortingEnabled = self.searchIndexList.isSortingEnabled()
        self.searchIndexList.setSortingEnabled(False)
        item = self.searchIndexList.item(0)
        item.setText(_translate("MainWindow", "All"))
        item = self.searchIndexList.item(1)
        item.setText(_translate("MainWindow", "Appliances"))
        item = self.searchIndexList.item(2)
        item.setText(_translate("MainWindow", "ArtsAndCrafts"))
        item = self.searchIndexList.item(3)
        item.setText(_translate("MainWindow", "Automotive"))
        item = self.searchIndexList.item(4)
        item.setText(_translate("MainWindow", "Baby"))
        item = self.searchIndexList.item(5)
        item.setText(_translate("MainWindow", "Beauty"))
        item = self.searchIndexList.item(6)
        item.setText(_translate("MainWindow", "Electronics"))
        item = self.searchIndexList.item(7)
        item.setText(_translate("MainWindow", "HealthPersonalCare"))
        item = self.searchIndexList.item(8)
        item.setText(_translate("MainWindow", "HomeGarden"))
        item = self.searchIndexList.item(9)
        item.setText(_translate("MainWindow", "Industrial"))
        item = self.searchIndexList.item(10)
        item.setText(_translate("MainWindow", "LawnAndGarden"))
        item = self.searchIndexList.item(11)
        item.setText(_translate("MainWindow", "MusicalInstruments"))
        item = self.searchIndexList.item(12)
        item.setText(_translate("MainWindow", "OfficeProducts"))
        item = self.searchIndexList.item(13)
        item.setText(_translate("MainWindow", "PetSupplies"))
        item = self.searchIndexList.item(14)
        item.setText(_translate("MainWindow", "PCHardware"))
        item = self.searchIndexList.item(15)
        item.setText(_translate("MainWindow", "SportingGoods"))
        item = self.searchIndexList.item(16)
        item.setText(_translate("MainWindow", "Tools"))
        item = self.searchIndexList.item(17)
        item.setText(_translate("MainWindow", "Toys"))
        item = self.searchIndexList.item(18)
        item.setText(_translate("MainWindow", "VideoGames"))
        item = self.searchIndexList.item(19)
        item.setText(_translate("MainWindow", "Wireless"))
        self.searchIndexList.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Price:"))
        self.minPriceSearchBox.setPrefix(_translate("MainWindow", "$"))
        self.label_4.setText(_translate("MainWindow", "to"))
        self.maxPriceSearchBox.setPrefix(_translate("MainWindow", "$"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.cancelSearchButton.setText(_translate("MainWindow", "Cancel"))
        self.filterGroup.setTitle(_translate("MainWindow", "Filters"))
        self.applyFiltersButton.setText(_translate("MainWindow", "Apply"))
        self.revertFiltersButton.setText(_translate("MainWindow", "Revert"))
        self.label_5.setText(_translate("MainWindow", "From:"))
        self.filterDateBox.setItemText(0, _translate("MainWindow", "All results"))
        self.filterDateBox.setItemText(1, _translate("MainWindow", "Last search only"))
        self.filterDateBox.setItemText(2, _translate("MainWindow", "Today\'s results only"))
        self.filterDateBox.setItemText(3, _translate("MainWindow", "Only watched products"))
        self.label_10.setText(_translate("MainWindow", "Show:"))
        self.primeCheck.setText(_translate("MainWindow", "Prime"))
        self.amazonCheck.setText(_translate("MainWindow", "Amazon"))
        self.privateLabelCheck.setText(_translate("MainWindow", "Private label"))
        self.restrictedCheck.setText(_translate("MainWindow", "Restricted categories"))
        self.zeroesCheck.setText(_translate("MainWindow", "Zeroes"))
        self.label_6.setText(_translate("MainWindow", "Offers:"))
        self.label_9.setText(_translate("MainWindow", "max"))
        self.label_7.setText(_translate("MainWindow", "Price:"))
        self.minPriceFilterBox.setPrefix(_translate("MainWindow", "$"))
        self.label_8.setText(_translate("MainWindow", "to"))
        self.maxPriceFilterBox.setPrefix(_translate("MainWindow", "$"))
        self.label_36.setText(_translate("MainWindow", "With keywords:"))
        self.label_37.setText(_translate("MainWindow", "Without keywords:"))
        self.label_32.setText(_translate("MainWindow", "Ranking:"))
        self.label_33.setText(_translate("MainWindow", "Weight:"))
        self.label_34.setText(_translate("MainWindow", "Volume:"))
        self.weightFilterBox.setSuffix(_translate("MainWindow", " lbs"))
        self.volumeFilterBox.setSuffix(_translate("MainWindow", " in³"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Status:"))
        self.searchStatusList.setSortingEnabled(False)
        self.clearSearchStatusBtn.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.searchTab), _translate("MainWindow", "Search && Filter"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Product Information:"))
        self.label_14.setText(_translate("MainWindow", "Manufacturer:"))
        self.label_15.setText(_translate("MainWindow", "Part Number:"))
        self.label_20.setText(_translate("MainWindow", "ASIN:"))
        self.label_12.setText(_translate("MainWindow", "Product Group:"))
        self.label_21.setText(_translate("MainWindow", "Category:"))
        self.label_22.setText(_translate("MainWindow", "Sales Rank:"))
        self.label_16.setText(_translate("MainWindow", "UPC:"))
        self.groupBox.setTitle(_translate("MainWindow", "Title && Link:"))
        self.label_13.setText(_translate("MainWindow", "Title:"))
        self.label_11.setText(_translate("MainWindow", "URL:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Sales Metrics:"))
        self.label_25.setText(_translate("MainWindow", "My Cost:"))
        self.myPriceBox.setPrefix(_translate("MainWindow", "$"))
        self.label_26.setText(_translate("MainWindow", "FBA Fees:"))
        self.fbaFeesBox.setPrefix(_translate("MainWindow", "$"))
        self.getFBAFeesButton.setText(_translate("MainWindow", "Get..."))
        self.label_23.setText(_translate("MainWindow", "My Price:"))
        self.label_35.setText(_translate("MainWindow", "Offers:"))
        self.prodPriceBox.setPrefix(_translate("MainWindow", "$"))
        self.label_24.setText(_translate("MainWindow", "Current Price:"))
        self.myCostBox.setPrefix(_translate("MainWindow", "$"))
        self.label_31.setText(_translate("MainWindow", "Margin:"))
        self.label_30.setText(_translate("MainWindow", "Monthly Profit:"))
        self.monthlyCostBox.setPrefix(_translate("MainWindow", "$"))
        self.label_29.setText(_translate("MainWindow", "Monthly Cost:"))
        self.marginBox.setSuffix(_translate("MainWindow", "%"))
        self.label_28.setText(_translate("MainWindow", "Monthly Volume:"))
        self.monthlyProfitBox.setPrefix(_translate("MainWindow", "$"))
        self.getVolumeButton.setText(_translate("MainWindow", "Get..."))
        self.label_27.setText(_translate("MainWindow", "Profit (ea.):"))
        self.profitEachBox.setPrefix(_translate("MainWindow", "$"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tools:"))
        self.openAmazonButton.setText(_translate("MainWindow", "Amazon..."))
        self.openGoogleButton.setText(_translate("MainWindow", "Google..."))
        self.openCamelButton.setText(_translate("MainWindow", "CamelCamelCamel..."))
        self.upcLookupButton.setText(_translate("MainWindow", "UPC Lookup..."))
        self.updateButton.setText(_translate("MainWindow", "Update..."))
        self.groupBox_6.setTitle(_translate("MainWindow", "History:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.detailTab), _translate("MainWindow", "Detail View"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuActions.setTitle(_translate("MainWindow", "Actions"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionEdit_Categories.setText(_translate("MainWindow", "Edit Categories..."))
        self.actionUpdate_Watched.setText(_translate("MainWindow", "Update all Watched"))
        self.actionRecalculate_Rankings.setText(_translate("MainWindow", "Recalculate Rankings"))
        self.actionShow_Graph.setText(_translate("MainWindow", "Show Graph"))
        self.actionShow_Table.setText(_translate("MainWindow", "Show Table"))

